name: Unit tests

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  pull_request:
    paths:
      - .github/workflows/test.yml
      - Cargo.toml
      - Cargo.lock
      - src/**/*.rs
      - python/**/*.py
      - tests/**/*.py
      - uv.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - Cargo.toml
      - Cargo.lock
      - src/**/*.rs
      - python/**/*.py
      - tests/**/*.py
      - uv.lock

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.os }} - python:${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"

      - uses: extractions/setup-just@v3

      - name: Run tests
        run: just test